(* ::Package:: *)

(* ::Text:: *)
(*Written December 20th, 2019.*)
(*Finished December 21st, 2019.*)


(* ::Subsubsection:: *)
(*Import*)


(* ::Input:: *)
(**)


(* ::Input:: *)
(*input=Characters/@StringSplit[Import[FileNameJoin[{NotebookDirectory[],"Day20Input.txt"}]],"\n"];*)
(*newInput=input;*)
(*outer={};*)
(*inner={};*)
(*Do[*)
(*If[input[[i,j]]==".",*)
(*Which[*)
(*UpperCaseQ[input[[i-1,j]]],*)
(*newInput[[i,j]]=StringJoin[input[[i-2,j]],input[[i-1,j]]];*)
(*newInput[[i-2,j]]=" ";newInput[[i-1,j]]=" ";*)
(*AppendTo[outer,{i,j}->newInput[[i,j]]],*)
(**)
(*UpperCaseQ[input[[i+1,j]]],*)
(*newInput[[i,j]]=StringJoin[input[[i+1,j]],input[[i+2,j]]];*)
(*newInput[[i+1,j]]=" ";newInput[[i+2,j]]=" ";*)
(*AppendTo[inner,{i,j}->newInput[[i,j]]],*)
(**)
(*UpperCaseQ[input[[i,j-1]]],*)
(*newInput[[i,j]]=StringJoin[input[[i,j-2]],input[[i,j-1]]];*)
(*newInput[[i,j-2]]=" ";newInput[[i,j-1]]=" ";*)
(*AppendTo[outer,{i,j}->newInput[[i,j]]],*)
(**)
(*UpperCaseQ[input[[i,j+1]]],*)
(*newInput[[i,j]]=StringJoin[input[[i,j+1]],input[[i,j+2]]];*)
(*newInput[[i,j+1]]=" ";newInput[[i,j+2]]=" ";*)
(*AppendTo[inner,{i,j}->newInput[[i,j]]]*)
(*]*)
(*],*)
(*{i,Length[input]},{j,Length[input[[i]]]}];*)
(**)


(* ::Input:: *)
(**)


(* ::Subsubsection:: *)
(*Part 1*)


(* ::Input:: *)
(*position=FirstPosition[newInput,"AA"];*)
(*board=Flatten[Table[{i,j}->newInput[[i,j]],{i,Length[newInput]},{j,Length[newInput[[i]]]}]];*)
(*viewBoard=SparseArray[board];*)
(**)
(*style={Background->GrayLevel[0],BaseStyle->{Directive[White,EdgeForm[],Opacity[1]]},VertexShapeFunction->(Rectangle[#1+.16,#1-.16]&),EdgeShapeFunction->(Rectangle[#1[[1]]+.16,#1[[2]]-.16]&)};*)
(*g=Graph[*)
(*Union[Flatten[Table[*)
(*If[*)
(*!StringContainsQ[viewBoard[[i,j]],"#"|" "],*)
(*{If[!StringContainsQ[viewBoard[[i+1,j]],"#"|" "],ToString[{i,j}]\[UndirectedEdge]ToString[{i+1,j}]],*)
(*If[!StringContainsQ[viewBoard[[i,j+1]],"#"|" "],ToString[{i,j}]\[UndirectedEdge]ToString[{i,j+1}]]}*)
(*],{i,Length[newInput]},{j,Length[newInput[[i]]]}]]][[2;;]]];*)
(*g=EdgeAdd[*)
(*g,*)
(*ToString[#[[1]]]\[UndirectedEdge]ToString[#[[2]]]&/@Select[GatherBy[Select[board,UpperCaseQ[#[[2]]]&],#[[-1]]&][[;;,;;,1]],Length[#]==2&]]*)


(* ::Input:: *)
(*GraphDistance[g,ToString[FirstPosition[newInput,"AA"]],ToString[FirstPosition[newInput,"ZZ"]]]*)


(* ::Subsubsection:: *)
(*Part 2*)


(* ::Input:: *)
(*position=FirstPosition[newInput,"AA"];*)
(*board=Flatten[Table[{i,j}->newInput[[i,j]],{i,Length[newInput]},{j,Length[newInput[[i]]]}]];*)
(*viewBoard=SparseArray[board];*)
(**)
(*style={Background->GrayLevel[0],BaseStyle->{Directive[White,EdgeForm[],Opacity[1]]},VertexShapeFunction->(Rectangle[#1+.16,#1-.16]&),EdgeShapeFunction->(Rectangle[#1[[1]]+.16,#1[[2]]-.16]&)};*)
(*g=Graph[*)
(*Union[Flatten[Table[*)
(*If[*)
(*!StringContainsQ[viewBoard[[i,j]],"#"|" "],*)
(*{If[!StringContainsQ[viewBoard[[i+1,j]],"#"|" "],ToString[{i,j}]\[UndirectedEdge]ToString[{i+1,j}]],*)
(*If[!StringContainsQ[viewBoard[[i,j+1]],"#"|" "],ToString[{i,j}]\[UndirectedEdge]ToString[{i,j+1}]]}*)
(*],{i,Length[newInput]},{j,Length[newInput[[i]]]}]]][[2;;]]];*)
(**)
(*inner=SortBy[*)
(*Select[board,UpperCaseQ[#[[2]]]&],*)
(*Max@Abs[#[[1]]-1/2 Dimensions[newInput]]&][[;;27]];*)
(*outer=SortBy[*)
(*Select[board,UpperCaseQ[#[[2]]]&],*)
(*Max@Abs[#[[1]]-1/2 Dimensions[newInput]]&][[28;;]];*)
(**)
(*topLevel=Select[*)
(*Flatten[Table[{o[[2]]<>"0"\[UndirectedEdge]i[[2]]<>"1",GraphDistance[g,ToString[o[[1]]],ToString[i[[1]]]]+1},{o,Select[outer,MemberQ[{"AA","ZZ"},#[[2]]]&]},{i,inner}],1],*)
(*#[[2]]=!=\[Infinity]&];*)
(*interLevelConnections=Select[*)
(*Flatten[*)
(*Table[{{o[[2]],i[[2]]},GraphDistance[g,ToString[o[[1]]],ToString[i[[1]]]]+1},{o,Select[outer,!MemberQ[{"AA","ZZ"},#[[2]]]&]},{i,inner}],1],*)
(*#[[2]]=!=\[Infinity]&];*)
(*intraLevelConnections=*)
(*Join[*)
(*DeleteDuplicates[*)
(*{Sort[#[[1]]],#[[2]]}&/@Select[*)
(*Flatten[*)
(*Table[{{o1[[2]],o2[[2]]},GraphDistance[g,ToString[o1[[1]]],ToString[o2[[1]]]]+1},{o1,Select[outer,!MemberQ[{"AA","ZZ"},#[[2]]]&]},{o2,Select[outer,!MemberQ[{"AA","ZZ"},#[[2]]]&]}],1],*)
(*#[[2]]=!=\[Infinity]\[And]#[[2]]=!=0&]*)
(*],*)
(*DeleteDuplicates[*)
(*{Sort[#[[1]]],#[[2]]}&/@Select[*)
(*Flatten[*)
(*Table[{{i1[[2]],i2[[2]]},GraphDistance[g,ToString[i1[[1]]],ToString[i2[[1]]]]+1},{i1,Select[inner,!MemberQ[{"AA","ZZ"},#[[2]]]&]},{i2,Select[inner,!MemberQ[{"AA","ZZ"},#[[2]]]&]}],1],*)
(*#[[2]]=!=\[Infinity]\[And]#[[2]]=!=0&]*)
(*]];*)
(*bottomLevels=Flatten[*)
(*Table[*)
(*Join[*)
(*{#[[1,1]]<>ToString[n]\[UndirectedEdge]#[[1,2]]<>ToString[n+1],#[[2]]}&/@interLevelConnections,*)
(*{#[[1,1]]<>ToString[n]\[UndirectedEdge]#[[1,2]]<>ToString[n],#[[2]]}&/@intraLevelConnections*)
(*],*)
(*{n,25}],*)
(*1];*)


(* ::Input:: *)
(**)


(* ::Input:: *)
(*GraphDistance[*)
(*Graph[#[[1]],EdgeWeight->#[[2]]]&@Transpose[Join[topLevel,bottomLevels]],*)
(*"AA0","ZZ0"]-1*)
