(* ::Package:: *)

(* ::Text:: *)
(*Written December 5th, 2019.*)


(* ::Subsubsection:: *)
(*Import*)


(* ::Input:: *)
(*input=Import[FileNameJoin[{NotebookDirectory[],"Day5Input.txt"}],"List"];*)
(*input=(ToExpression@(StringSplit[#,","]&/@input))[[1]];*)


(* ::Input:: *)
(*outputValue*)


(* ::Subsubsection:: *)
(*Part 1*)


(* ::Input:: *)
(*AbsoluteTiming[*)
(*newInput=input;*)
(*stepList={newInput};*)
(*inputValue=1;*)
(*outputValue=0;*)
(*i=1;*)
(*jump=1;*)
(*While[newInput[[i]]!=99,*)
(*fullOpCode=*)
(*PadLeft[IntegerDigits[newInput[[i]]],*)
(*IntegerDigits[newInput[[i]]][[-1]]/.{1->5,2->5,3->3,4->3}];*)
(*opCode=FromDigits[fullOpCode[[-2;;]]];*)
(*parameterModes=fullOpCode[[;;-3]];*)
(*parameters=Table[*)
(*If[j==1,*)
(*If[parameterModes[[j]]==0,*)
(*newInput[[i+Length[parameterModes]-j+1]]+1,*)
(*i+Length[parameterModes]-j+1],*)
(*If[parameterModes[[j]]==0,*)
(*newInput[[newInput[[i+Length[parameterModes]-j+1]]+1]],*)
(*newInput[[i+Length[parameterModes]-j+1]]]*)
(*],*)
(*{j,Length[parameterModes]}];*)
(*jump=Length[parameterModes]+1;*)
(**)
(*Which[*)
(*opCode==1,*)
(*newInput[[parameters[[1]]]]=Expand[parameters[[2]]+parameters[[3]]],*)
(**)
(*opCode==2,*)
(*newInput[[parameters[[1]]]]=Expand[parameters[[2]]*parameters[[3]]],*)
(**)
(*opCode==3,*)
(*newInput[[parameters[[1]]]]=inputValue,*)
(**)
(*opCode==4,*)
(*outputValue=newInput[[parameters[[1]]]],*)
(**)
(*opCode==99\[Or]i>Length[newInput],*)
(*Break[]*)
(*];*)
(*i+=jump;*)
(*AppendTo[stepList,newInput];*)
(*];*)
(*outputValue]*)


(* ::Subsubsection:: *)
(*Part 2*)


(* ::Input:: *)
(*AbsoluteTiming[*)
(*newInput=input;*)
(*stepList={newInput};*)
(*inputValue=5;*)
(*outputValue=0;*)
(*i=1;*)
(*jump=1;*)
(*counter=0;*)
(*While[newInput[[i]]!=99,*)
(*fullOpCode=*)
(*PadLeft[IntegerDigits[newInput[[i]]],*)
(*IntegerDigits[newInput[[i]]][[-1]]/.{1->5,2->5,3->3,4->3,5->4,6->4,7->5,8->5}];*)
(*opCode=FromDigits[fullOpCode[[-2;;]]];*)
(*parameterModes=fullOpCode[[;;-3]];*)
(*parameters=Table[*)
(*temp=i+Length[parameterModes]-j+1;*)
(*If[parameterModes[[j]]==0,*)
(*newInput[[temp]]+1,*)
(*temp],*)
(*{j,Length[parameterModes]}];*)
(*jump=Length[parameterModes]+1;*)
(*Which[*)
(*opCode==1,*)
(*newInput[[parameters[[1]]]]=Expand[newInput[[parameters[[2]]]]+newInput[[parameters[[3]]]]],*)
(**)
(*opCode==2,*)
(*newInput[[parameters[[1]]]]=Expand[newInput[[parameters[[2]]]]*newInput[[parameters[[3]]]]],*)
(**)
(*opCode==3,*)
(*newInput[[parameters[[1]]]]=inputValue,*)
(**)
(*opCode==4,*)
(*outputValue=newInput[[parameters[[1]]]],*)
(**)
(*opCode==5,*)
(*If[newInput[[parameters[[2]]]]!=0,*)
(*i=newInput[[parameters[[1]]]]+1;*)
(*jump=0],*)
(**)
(*opCode==6,*)
(*If[newInput[[parameters[[2]]]]==0,*)
(*i=newInput[[parameters[[1]]]]+1;*)
(*jump=0],*)
(**)
(*opCode==7,*)
(*If[newInput[[parameters[[3]]]]<newInput[[parameters[[2]]]],*)
(*newInput[[parameters[[1]]]]=1,*)
(*newInput[[parameters[[1]]]]=0],*)
(**)
(*opCode==8,*)
(*If[newInput[[parameters[[3]]]]==newInput[[parameters[[2]]]],*)
(*newInput[[parameters[[1]]]]=1,*)
(*newInput[[parameters[[1]]]]=0],*)
(**)
(*opCode==99\[Or]i>Length[newInput],*)
(*Break[]*)
(*];*)
(*counter++;*)
(*If[counter>10000,*)
(*Print["Infinite Loop"];*)
(*Break[]];*)
(*i+=jump;*)
(*AppendTo[stepList,newInput];*)
(*];*)
(*outputValue]*)
