(* ::Package:: *)

(* ::Text:: *)
(*Written December 5th, 2019.*)


(* ::Subsubsection:: *)
(*Import*)


(* ::Input:: *)
(*input=Import[FileNameJoin[{NotebookDirectory[],"Day5Input.txt"}],"List"];*)
(*input=(ToExpression@(StringSplit[#,","]&/@input))[[1]];*)


(* ::Input:: *)
(*runIntcode[inputList_List,inputValue_Integer,OptionsPattern[{"OutputSteps"->False}]]:=*)
(*Module[{*)
(*newInput=inputList,*)
(*stepList={},*)
(*outputValue=0,*)
(**)
(*padLengths={1->5,2->5,3->3,4->3,5->4,6->4,7->5,8->5},*)
(**)
(*i,jump,counter,*)
(*fullOpCode,opCode,parameterModes,parameters*)
(*},*)
(**)
(*i=1;jump=1;counter=0;*)
(**)
(*While[newInput[[i]]!=99,*)
(*fullOpCode=*)
(*PadLeft[IntegerDigits[newInput[[i]]],*)
(*IntegerDigits[newInput[[i]]][[-1]]/.padLengths];*)
(*opCode=FromDigits[fullOpCode[[-2;;]]];*)
(*parameterModes=Reverse[fullOpCode[[;;-3]]];*)
(*parameters=Table[*)
(*If[parameterModes[[j]]==0,*)
(*newInput[[i+j]]+1,*)
(*i+j],*)
(*{j,Length[parameterModes]}];*)
(*jump=Length[parameterModes]+1;*)
(**)
(*If[OptionValue["OutputSteps"],*)
(*AppendTo[stepList,*)
(*Join[newInput[[i;;i+Length[parameterModes]]]]]];*)
(**)
(*Which[*)
(*opCode==1,*)
(*newInput[[parameters[[3]]]]=Expand[newInput[[parameters[[2]]]]+newInput[[parameters[[1]]]]],*)
(**)
(*opCode==2,*)
(*newInput[[parameters[[3]]]]=Expand[newInput[[parameters[[2]]]]*newInput[[parameters[[1]]]]],*)
(**)
(*opCode==3,*)
(*newInput[[parameters[[1]]]]=inputValue,*)
(**)
(*opCode==4,*)
(*outputValue=newInput[[parameters[[1]]]],*)
(**)
(*opCode==5,*)
(*If[newInput[[parameters[[1]]]]!=0,*)
(*i=newInput[[parameters[[2]]]]+1;*)
(*jump=0],*)
(**)
(*opCode==6,*)
(*If[newInput[[parameters[[1]]]]==0,*)
(*i=newInput[[parameters[[2]]]]+1;*)
(*jump=0],*)
(**)
(*opCode==7,*)
(*If[newInput[[parameters[[1]]]]<newInput[[parameters[[2]]]],*)
(*newInput[[parameters[[3]]]]=1,*)
(*newInput[[parameters[[3]]]]=0],*)
(**)
(*opCode==8,*)
(*If[newInput[[parameters[[1]]]]==newInput[[parameters[[2]]]],*)
(*newInput[[parameters[[3]]]]=1,*)
(*newInput[[parameters[[3]]]]=0],*)
(**)
(*opCode==99\[Or]i>Length[newInput],*)
(*Break[]*)
(*];*)
(*counter++;*)
(*If[counter>10000,*)
(*Print["Infinite Loop"];*)
(*Break[]];*)
(*i+=jump;*)
(*];*)
(*If[*)
(*OptionValue["OutputSteps"],*)
(*{outputValue,stepList},*)
(*outputValue]*)
(*]*)


(* ::Subsubsection:: *)
(*Part 1*)


(* ::Input:: *)
(*AbsoluteTiming[runIntcode[input,1]]*)


(* ::Subsubsection:: *)
(*Part 2*)


(* ::Input:: *)
(*AbsoluteTiming[runIntcode[input,5]]*)
